### ISSUE TITLE
tsconfig not found

### ISSUE THREAD

**Issue by leye0** [web-dave/ng2-dg#1]
https://github.com/web-dave/ng2-dg/blob/master/src/extension.ts#L19

Isn't tsconfig in the /src folder and not in the / folder?

Currently, the extensions is not working in my project because it looks for the tsconfig.json at the wrong place.

It executes directly in the opened folder. i.e.  c:/NG2/DemoApp/ 

`"tsconfig.json" file was not found in the current directory. `

**Comment by web-dave** [comment]
Thx for this feedback. Work in progress.

**Comment by web-dave** [comment]
Publishe the new version.
give it a try please.

**Comment by web-dave** [comment]
new workflow! start plugin, select folde from dropdown. wait

**Comment by leye0** [comment]
Thanks a lot! Tested and working. It didn't work in another project where tsconfig.json is at the root, however.

**Comment by web-dave** [comment]
OK, I'll fix this tonight.

**Comment by web-dave** [comment]
fixed in v0.1.7
